config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :users, :sessions

  resources :teams do
    resources :players
  end

  resources :leagues do
    resources :teams
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  get '/users/players'
  get '/users/teams'
  get '/users/league'

  get '/join_league' =>'leagues#index'
  get '/join_league/:id' =>'teams#new', as: "join_a_league"
  post '/leagues/:id' => 'leagues#update'

  get '/auth/:provider/callback' => 'omniauth_callbacks#create', as: "authorize"
  get '/auth/failure', to: redirect('/')

end

app/models/league.rb
class League < ActiveRecord::Base
  # belongs_to :player #Player must keep track of which league its in... for that specific player (keep track of which player exists/doesn't exist)

  has_many :teams
  has_many :users, through: :teams

  validates_presence_of :name
  validates_uniqueness_of :name, message: "- league name already exists!"

end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

  def new
    @league = League.new
  end

  def index
    @leagues = League.all

    if session[:user_id]
      @user = User.find(session[:user_id])
    end
  end

  def edit
    @league = League.find(params[:id])
  end

  def create
    @league = League.new(league_params)
    if @league.save
      redirect_to league_path(@league)
    else
      flash[:error]="#{@league.errors.full_messages.join(". ")}"
      render :new
    end
  end

  def show
    @league = League.find_by(id: params[:id]) || League.find_by(name: params[:id])
    @teams = @league.teams
  end

  def update
    @league = League.find(params[:id])
    @league.update(league_params)
    if @league.save
      redirect_to league_path(@league)
    else
      render :edit
    end
  end

  def destroy

  end


  def join_league
    @user = current_user
    @league = League.find(params[:id])
    redirect_to new_team_path(@league)
  end

  private

  def league_params
    params.require(:league).permit(:name)
  end

end

app/helpers/leagues_helper.rb
module LeaguesHelper

  def league_name?(id)
    league = League.find_by(id: id)
    @lname = league.name
  end
end

app/views/leagues/_league_form.html.erb
<%= form_for(@league) do |a| %>
  <%= a.label :name %>
  <%= a.text_field :name %> <br><br>

  <%= a.submit %>
<% end %>

app/views/leagues/edit.html.erb
<h2> Edit your league name here: </h2>

<%= render 'league_form' %> 

app/views/leagues/index.html.erb
<h1> Welcome! Below are the leagues available</h1>
<p> Click join to submit your team name and compete against the best </p>

<table class="table table-hover players">
  <thead>
    <tr>
      <th> No. </th>
      <th> League Name</th>
      <th> Current # of Teams</th>
      <th> Join League </th>
    </tr>
  </thead>

  <tbody>
    <% @leagues.each_with_index do |l, index| %>
      <tr>
        <td> <%= index + 1%> </td>
        <td> <%= link_to "#{l.name}", l  %> </td>
        <td> <%= l.teams.count %> </td>
        <td> <%= link_to "Join", join_a_league_path(l.id) %> </td>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/leagues/new.html.erb
<h3> Enter your new league name here: </h3>

<%= render 'league_form' %> 

app/views/leagues/show.html.erb
<h1> Welcome to the <%= @league.name %> page</h1>

<h3> Here are all the teams currently in your league: </h3>

<% if current_user.admin %>
  <%= link_to "Create Team as Admin", new_league_team_path(@league.id), :id => "admin-create-id", :data => {:confirm => "You Sure You Want To Create A Team For Someone Else?"}  %>
<% end %>

<table class="table table-hover players">
  <thead>
    <tr>
      <th> No. </th>
      <th> Team Name </th>
      <th> Owner </th>
    </tr>
  </thead>
  <tbody>
    <% @teams.each_with_index do |t, index| %>
      <tr>
        <td> <%= index + 1%> </td>
        <td> <%= link_to "#{t.name}", t  %></td>
        <td> <%= link_to "#{t.user.name}", user_path(t.user.id) %> </td>
      </tr>
    <%end%>
  </tbody>
</table>

  <p> <%= link_to "Back to home", user_path(current_user) %> </p>