config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :users, :sessions

  resources :teams do
    resources :players
  end

  resources :leagues do
    resources :teams
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  get '/users/players'
  get '/users/teams'
  get '/users/league'

  get '/join_league' =>'leagues#index'
  get '/join_league/:id' =>'teams#new', as: "join_a_league"
  post '/leagues/:id' => 'leagues#update'

  get '/auth/:provider/callback' => 'omniauth_callbacks#create', as: "authorize"
  get '/auth/failure', to: redirect('/')

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      flash[:error] = "#{@user.errors.full_messages.join(". ")}"
      render 'new'
    end
  end

  def show
    if params[:id]
      @user = User.find(params[:id])
    elsif session[:user_id]
      @user = User.find(session[:user_id])
    else
      redirect_to '/'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user.update(user_params)  #only parameter by default is ID, so this is a security thing (user_params - private method)
    if @user.save
      redirect_to @user
    else
      flash[:error] = "#{@user.errors.full_messages.join(". ")}"
      render 'edit'
    end
  end

  def destroy
    session[:user_id] = nil
    @user.destroy
  end


private

  def set_user
      @user = User.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(
        :name,
        :password,
        :email,
        :admin
      )
    end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_form.html.erb
<%= form_for(@user) do |u| %>
  <%= u.label :name %>
  <%= u.text_field :name %><br>

  <%= u.label :email %>
  <%= u.text_field :email %><br>

  <%= u.label :password %>
  <%= u.text_field :password %><br><br>

  <%= u.label :admin %>
  <%= u.check_box :admin %> <br><br>

  <%= u.submit %>
<% end %>

app/views/users/_table.html.erb
<% unless user_check(@user.id) %>
  <h3> <%= "Here are #{@user.name}'s leagues and teams" %> </h3>
<% end %>

<table class="table table-hover players">
    <thead>
      <tr>
        <th> No. </th>
        <th> League Name </th>
        <% if @user.admin %>
          <th> Admin Action </th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @user.leagues.each_with_index do |l, index| %>
        <tr>
          <td> <%= index + 1%> </td>
          <td> <%= link_to "#{l.name}", l  %></td>
          <% if @user.admin %>
            <td> <%= link_to "Edit League", edit_league_path(l)%> </td>
          <% end %>
        </tr>
      <%end%>
  </tbody>
</table>

  <% if user_check(@user.id) %>
    <h3> Here are your teams:</h3>
  <% end  %>

  <table class="table table-hover players">
      <thead>
        <tr>
          <th> No. </th>
          <th> Team Name </th>
          <th> League Name </th>
          <% if user_check(@user.id) %>
            <th> Edit Team </th>
            <th> Delete Team </th>
          <%end %>
        </tr>
      </thead>
      <tbody>
        <% @user.teams.each_with_index do |t, index| %>
          <tr>
            <td> <%= index + 1%> </td>
            <td> <%= link_to "#{t.name}", t %> </td>
            <td> <%= link_to "#{league_name?(t.league_id)}", league_path(league_name?(t.league_id)) %> </td>
            <% if user_check(@user.id) %>
              <td> <%= link_to "Edit", edit_team_path(t) %> </td>
              <td> <%= link_to 'Delete', team_path(t), method: :delete %></td>
            <% end %>
          </tr>
        <%end%>
    </tbody>
  </table>
  <br>
  
  <% if @user.admin && user_check(@user.id) %>
    <p> <%= link_to "Create A New League", new_league_path %> </p>
    <p> <%= link_to "Join A League", join_league_path %>  </p>
  <% elsif user_check(@user.id) %>
    <p> <%= link_to "Join A New League", join_league_path %> </p>
  <% end %>

app/views/users/_table2.html.erb
<h3>Here are your leagues: </h3>

<table class="table table-hover players">
    <thead>
      <tr>
        <th> No. </th>
        <th> League Name </th>
        <th> Admin Action </th>
      </tr>
    </thead>
    <tbody>
      <% @user.leagues.each_with_index do |l, index| %>
        <tr>
          <td> <%= index + 1%> </td>
          <td> <%= link_to "#{l.name}", l  %></td>
          <td> <%= link_to "Edit League", edit_league_path(l)%> </td>
        </tr>
      <%end%>
  </tbody>
</table>

<h3> Here are your teams:</h3>

  <table class="table table-hover players">
      <thead>
        <tr>
          <th> No. </th>
          <th> Team Name </th>
          <th> Admin Action </th>
        </tr>
      </thead>
      <tbody>
        <% @user.teams.each_with_index do |t, index| %>
          <tr>
            <td> <%= index + 1%> </td>
            <td> <%= link_to "#{t.name}", t %> </td>
            <td> <%= link_to "Edit Team", edit_team_path(t) %> </td>
          </tr>
        <%end%>
    </tbody>
  </table>

app/views/users/edit.html.erb
<h3> Edit and submit your updated User information here </h3>

<%= render 'form' %>

app/views/users/new.html.erb
<h3>Welcome to FF Basketball! Sign Up as new user below: </h3>
<p> Click the admin checkbox if you are going to be League Manager. There can only be one. </p>

<%= render 'form' %>

app/views/users/show.html.erb
<% if user_check(@user.id)%>
  <h1>Hi, <%= @user.name%>!</h1>
  <p> <%= link_to "Edit Your Information", edit_user_path(@user) %> <p>
<% else %>
  <h1>Checking out the competition, huh <%= current_user.name%>?!</h1>
<%end%>

  <%= render 'table' %> <br>